### ISSUE TITLE
capital_P_dangit()

### ISSUE THREAD

**Issue by boogah** [espreto/wpsploit#1]
Just a friendly — albeit pedantic — heads up...

It's WordPress, not Wordpress. :wink:

**Comment by espreto** [comment]
OMG! As I did not see it? Thank you for reporting this @boogah. :+1: 

Fixed via: 65239883b4f94a03a11b6429e45c2c7cb5c0e1d0 and 2ceb71f0e8710f56b27796fe3ffaa41134829b51

**Comment by boogah** [comment]
I fixed this everywhere I could find it in #2, if you're interested.
